apiVersion: v1
kind: Service
metadata:
  name: {{ include "libra-reference-wallet.fullname" . }}-frontend
  labels:
    {{- include "libra-reference-wallet.labels" . | nindent 4 }}
    app: {{ include "libra-reference-wallet.fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "libra-reference-wallet.selectorLabels" . | nindent 4 }}
    app: {{ include "libra-reference-wallet.fullname" . }}-frontend
