version: '3.4'
services:
  gateway:
    volumes:
      - ../gateway/nginx.conf:/etc/nginx/nginx.conf

  backend-web-server:
    environment:
      - COMPOSE_ENV="development"
    ports:
      - "5000"
      - "${OFFCHAIN_SERVICE_PORT:-5091}"

  backend-worker:
    environment:
      - COMPOSE_ENV="development"

  backend-pubsub-worker:
    environment:
      - COMPOSE_ENV="development"

  liquidity:
    environment:
      - COMPOSE_ENV="development"
    ports:
      - "5000"

  # backend-offchain:
  #   environment:
  #     - COMPOSE_ENV="development"
  #     - OFFCHAIN_SERVICE_PORT=${OFFCHAIN_SERVICE_PORT:-8091}
  #   ports:
  #     - ${OFFCHAIN_SERVICE_PORT:-8091}
